project:
  type: book
  output-dir: ../_build
lang: de

book:
  title: "Julia und Jupyter Notebooks"
  subtitle: "Eine kurze Einführung für Anwendungen in der Numerik"
  author: "Matthias Baitsch"
  chapters:
    - index.qmd
    - 01-julia.qmd
    - 02-vektoren-und-matrizen.qmd
    - 03-plotten.qmd

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt
